CREATE TABLE orcamento (
    id INT AUTO_INCREMENT PRIMARY KEY,
    exercicio VARCHAR(10),
    nivel1 VARCHAR(255),
    nivel2 VARCHAR(255),
    nivel3 VARCHAR(255),
    nivel4 VARCHAR(255),
    classe_custo VARCHAR(255),
    descricao_despesa VARCHAR(255),
    divisao VARCHAR(255),
    empresa_rateio VARCHAR(255),
    descricao_empresa_rateio VARCHAR(255),
    centro_custo VARCHAR(255),
    texto_descritivo VARCHAR(255),
    prev_janeiro DECIMAL(15,2),
    prev_fevereiro DECIMAL(15,2),
    prev_marco DECIMAL(15,2),
    prev_abril DECIMAL(15,2),
    prev_maio DECIMAL(15,2),
    prev_junho DECIMAL(15,2),
    prev_julho DECIMAL(15,2),
    prev_agosto DECIMAL(15,2),
    prev_setembro DECIMAL(15,2),
    prev_outubro DECIMAL(15,2),
    prev_novembro DECIMAL(15,2),
    prev_dezembro DECIMAL(15,2)
); 